Remove ApiSegment from UUIDs of HttpClients/Servers and TcpClients/Servers
openBackhaul/OperationKeyManagement pull request #106
Opened 2022-12-13 09:19 UTC by kmohr-soprasteria

Fixes #98

2022-12-13 14:42 UTC, IswaryaaS approved these changes

2022-12-13 16:29 UTC, IswaryaaS requested changes

2022-12-13 16:29 UTC, IswaryaaS commented on OperationKeyManagement.yaml
>              post:
As per comment https://github.com/openBackhaul/ExecutionAndTraceLog/pull/153#discussion_r1047382078, can we also update TAR data to version 1.0.0 and it's corresponding ip-address and port details in line 1694 (example of /v1/list-applications)

2022-12-13 17:26 UTC, openBackhaul commented on OperationKeyManagement.yaml
>              post:
Changed protocol to HTTP, and adapted IP address and port to match with release number 1.0.0.

2022-12-14 02:24 UTC, IswaryaaS approved these changes

2022-12-14 08:26 UTC, merged