Support Version 2.0.0 changes for regard-application
openBackhaul/OperationKeyManagement pull request #150
Opened 2023-01-16 16:39 UTC by vanithavalluripalli9

Fixes #136

2023-01-16 16:41 UTC, vanithavalluripalli9 commented
Reviewer is @DanaSunal

2023-01-17 10:23 UTC, DanaSunal requested changes

2023-01-17 10:23 UTC, DanaSunal commented on server/api/openapi.yaml
> -          pattern: "([A-Z][a-z0-9]+){2,}"
Is this part of spec already?

2023-01-17 11:02 UTC, vanithavalluripalli9 commented on server/package.json
> +    "onf-core-model-ap": "~2.0.0-alpha.3"
Done

2023-01-17 11:03 UTC, vanithavalluripalli9 commented on server/api/openapi.yaml
> -          pattern: "([A-Z][a-z0-9]+){2,}"
No , it was added by mistake . So , removed it.

2023-01-17 13:44 UTC, DanaSunal approved these changes

2023-01-17 13:45 UTC, merged