Update callbacks for the service /v1/bequeath-your-data-and-die
openBackhaul/OperationKeyManagement pull request #160
Opened 2023-02-01 12:54 UTC by vanithavalluripalli9

Fixes #148

2023-02-01 14:00 UTC, vanithavalluripalli9 commented
Reviewer is @DanaSunal

2023-02-01 15:16 UTC, DanaSunal requested changes

2023-02-01 15:16 UTC, DanaSunal commented on server/service/individualServices/SoftwareUpgrade.js
> +        let newReleaseHttpClientUuid = (await logicalTerminationPoint.getServerLtpListAsync(newReleaseOperationClientUuid))[0];
You have already a function in this file that does this functionality, can you use it here? It's also valid for other callbacks.

2023-02-01 15:16 UTC, DanaSunal commented on server/service/individualServices/SoftwareUpgrade.js
> +        let subscriptionName = await OperationClientInterface.getOperationNameAsync(notifyLinkUpdatesOperationName);
'notifyLinkUpdatesOperationName' is confusing for a variable name, since it's not an operation name, but UUID.

2023-02-01 16:31 UTC, vanithavalluripalli9 commented on server/service/individualServices/SoftwareUpgrade.js
> +        let subscriptionName = await OperationClientInterface.getOperationNameAsync(notifyLinkUpdatesOperationName);
Done

2023-02-02 10:56 UTC, DanaSunal approved these changes

2023-02-02 10:56 UTC, merged