issue-280 : fixed trace-indicator generation
openBackhaul/OperationKeyManagement pull request #288
Opened 2023-08-22 12:29 UTC by DanaSunal

Fixes #280

2023-08-22 14:18 UTC, PrathibaJee requested changes

2023-08-22 14:18 UTC, PrathibaJee commented on server/utils/HttpClient.js
> +      this.#traceIndicator = traceIndicator + ".0";
Trace indicator count starts with 1. Shall we change ".0" to ".1".

2023-08-23 06:23 UTC, DanaSunal commented on server/utils/HttpClient.js
> +      this.#traceIndicator = traceIndicator + ".0";
No. This is just constructor. When the trace-indicator is first used, it's incremented (line 72). It's also explained in the comment on line 42.

2023-08-28 11:22 UTC, PrathibaJee commented on server/utils/HttpClient.js
> +      this.#traceIndicator = traceIndicator + ".0";
Thanks for the explanation.

2023-09-04 17:21 UTC, PrathibaJee approved these changes

2023-09-04 17:21 UTC, merged