Fix for issue Refactoring of bequeath-your-data-and-die as per the flow followed in other TinyApplicationControllers #31
openBackhaul/OperationKeyManagement pull request #35
Opened 2022-08-16 07:21 UTC by vanithavalluripalli9

Fixes issue Refactoring of bequeath-your-data-and-die as per the flow followed in other TinyApplicationControllers #31

2022-08-18 07:53 UTC, MartinSunal requested changes

2022-08-18 07:53 UTC, MartinSunal commented on server/service/individualServices/PrepareForwardingAutomation.js
> +    return new Promise(async function (resolve, reject) {
please, use indentation 2 spaces as in other files

2022-08-18 07:53 UTC, MartinSunal commented on server/service/individualServices/SoftwareUpgrade.js
> + const operationClientInterface = require('onf-core-model-ap/applicationPattern/onfModel/models/layerProtocols/OperationClientInterface');
every line in this file has a space at the beginning. Please, remove them and keep indentation 2 spaces.

2022-08-29 10:09 UTC, vanithavalluripalli9 commented on server/service/individualServices/PrepareForwardingAutomation.js
> +    return new Promise(async function (resolve, reject) {
fixed the issue

2022-08-29 10:11 UTC, vanithavalluripalli9 commented on server/service/individualServices/SoftwareUpgrade.js
> + const operationClientInterface = require('onf-core-model-ap/applicationPattern/onfModel/models/layerProtocols/OperationClientInterface');
fixed the issue

2022-08-29 11:39 UTC, MartinSunal commented on server/service/individualServices/SoftwareUpgrade.js
> +    return new Promise(async function (resolve, reject) {
as mentioned in my previous comment - please, use indentation 2 spaces everywhere

2022-08-30 09:53 UTC, MartinSunal approved these changes

2022-08-30 09:53 UTC, merged