Fixed usage of FC LinkUpdateNotificationCausesOperationKeyUpdates
openBackhaul/OperationKeyManagement pull request #45
Opened 2022-08-30 11:04 UTC by MartinSunal

- /v1/regard-application adds FC-port to LinkUpdateNotificationCausesOperationKeyUpdates
- /v1/disregard-application removes FC-port from LinkUpdateNotificationCausesOperationKeyUpdates
- /v1/regard-updated-link checks if endpoints of link-uuid are located in LTPs from FC-ports of LinkUpdateNotificationCausesOperationKeyUpdates

Fixes #42

Signed-off-by: Martin Sunal <martin.sunal@paxet.io>

2022-09-06 18:01 UTC, PrathibaJee requested changes

2022-09-06 18:01 UTC, PrathibaJee commented on server/service/IndividualServicesService.js
> +const FC_LINK_UPDATE_NOTIFICATION_CAUSES_OPERATION_KEY_UPDATES_UUID = 'okm-0-0-1-op-fc-3000';
Instead of referring the forwarding construct using UUID , can we refer it by using the forwarding-construct/name=ForwardingName . Reason for this request is , in future , based on the [Structure of UUIDs](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Names/StructureOfUuids/StructureOfUuids.md) UUIDs will be changed. But , ForwardingNames are more likely to change.

2022-09-13 08:02 UTC, MartinSunal commented on server/service/IndividualServicesService.js
> +const FC_LINK_UPDATE_NOTIFICATION_CAUSES_OPERATION_KEY_UPDATES_UUID = 'okm-0-0-1-op-fc-3000';
IMO, purpose of ID is that it is unique and represents the entity. There cannot be two entities with the same ID but there can be two entities with the same name. In case ID format is changed, it is expected to change it in a code. Also this okm-0-0-1-op-fc-3000 is hardcoded in config file and it cannot be changed during runtime so hardcoding in code cannot make any harm. If my understanding of IDs and names in context of AP applications is not correct, please explain and I can change all IDs in code to be names in separate PR.

2022-09-18 16:43 UTC, PrathibaJee commented on server/service/IndividualServicesService.js
> +const FC_LINK_UPDATE_NOTIFICATION_CAUSES_OPERATION_KEY_UPDATES_UUID = 'okm-0-0-1-op-fc-3000';
Your opinion is correct. 
The code delivered for the requirement of this version of the application never requires a change as its aligned with the load file of that version.

But , in the future upcoming release, the uuid format in all the application's load file and specification will be changed as per the [Structure of UUIDs](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Names/StructureOfUuids/StructureOfUuids.md).
And during the implementation of the new version , we also have to change all the uuids that are hardcoded in the OperationKeyManagement(OKM) application's source code.

That’s why I m suggesting to not hardcode the uuids of the forwarding constructs. 
Instead , you can hardcode the forwarding-name which will have less probability to change. 

Also , in other TinyApplicationControllers for better code maintainability , we are not hardcoding the logical-termination-point and forwarding-construct uuids until and unless if there is no other way reach that instance.

2022-09-20 07:41 UTC, MartinSunal commented on server/service/IndividualServicesService.js
> +const FC_LINK_UPDATE_NOTIFICATION_CAUSES_OPERATION_KEY_UPDATES_UUID = 'okm-0-0-1-op-fc-3000';
fixed in commit https://github.com/openBackhaul/OperationKeyManagement/pull/45/commits/4cfd19911ce58c2e632e6e6920f0f406864c0d02

2022-10-09 16:29 UTC, PrathibaJee approved these changes
Review comments are fixed as discussed. Many thanks.

2022-10-09 16:30 UTC, merged