Implemented behavior based on "operationName" value
openBackhaul/OperationKeyManagement pull request #47
Opened 2022-09-01 10:45 UTC by MartinSunal

This is behavior for each value:
- string-profile-1-0:STRING_VALUE_TYPE_PROTECTION
  - update key is done in every 5min
  - /v1/regard-updated-link does not update keys and returns status code 500
- string-profile-1-0:STRING_VALUE_TYPE_REACTIVE
  - update key does not execute periodically
  - /v1/regard-updated-link updates keys
- string-profile-1-0:STRING_VALUE_TYPE_OFF
  - update key does not execute periodically
  - /v1/regard-updated-link does not update keys and returns status code 500

Fixes #46

Signed-off-by: Martin Sunal <martin.sunal@paxet.io>

2022-09-06 17:56 UTC, PrathibaJee reviewed
Started testing the changes in local. Many thanks for the changes. Pull request will be approved after verifying the change in local.

2022-09-18 16:23 UTC, PrathibaJee requested changes
Overall the concept is working fine for the operation mode Protection, reactive and off. Also the transition from one state to another state is working fine.

Made two comments that requires minor changes. Thanks.

2022-09-18 16:23 UTC, PrathibaJee commented on server/service/StringProfileService.js
> +const operationModeStringValuePath = `${onfPaths.PROFILE}=okm-0-0-1-string-p-0000/string-profile-1-0:string-profile-pac/string-profile-configuration/string-value`;
The 'url' argument in `exports.putStringProfileStringValue = function (body, url)` will always carries the same path `/core-model-1-4:control-construct/profile-collection/profile=okm-0-0-1-string-p-0000/string-profile-1-0:string-profile-pac/string-profile-configuration/string-value` mentioned in the constant attribute "operationModeStringValuePath".
So , this hardcoded value can be removed and the 'url' argument from the function can be used instead.

2022-09-19 08:10 UTC, MartinSunal commented on server/service/IndividualServicesService.js
> +  if (operationModeValue !== profileConstants.OPERATION_MODE_REACTIVE) {
@PrathibaJee It has been implemented based on description from https://github.com/openBackhaul/OperationKeyManagement/issues/39:
```
description: >
  'reactive: a new value gets written into the operationKey attributes at server and connected clients, whenever a link update got notified (/v1/regard-updated-link)
   protection: new values get periodically written into the operationKey attributes at servers and connected clients
   off: no automated changes to the values of the operationKey attributes at servers or clients
  '
```

It is not explicitly defined how /v1/regard-updated-link should behave when operationMode is PROTECTION.
My understanding was that /v1/regard-updated-link should update operationKeys only when operationMode is REACTIVE.

Please, let me know what behavior is preferred and I can change accordingly.

2022-09-19 08:19 UTC, MartinSunal commented on server/service/StringProfileService.js
> +const operationModeStringValuePath = `${onfPaths.PROFILE}=okm-0-0-1-string-p-0000/string-profile-1-0:string-profile-pac/string-profile-configuration/string-value`;
It cannot be removed because it is used in `getOperationModeProfileStringValue` on line 92 and that function is called from `IndividualServicesService.regardUpdatedLink`, `IndividualServicesService.scheduleKeyRotation`, `IndividualServicesService.reccurentUpdateKeys` where url is not known or different.

2022-09-19 10:42 UTC, MartinSunal commented on server/service/IndividualServicesService.js
> +  if (operationModeValue !== profileConstants.OPERATION_MODE_REACTIVE) {
@openBackhaul what do you think, please? How should /v1/regard-updated-link behave in operationMode = PROTECTION?

2022-10-09 16:41 UTC, PrathibaJee commented
Changes are as per the latest decision in the issue https://github.com/openBackhaul/OperationKeyManagement/issues/39.
But the current branch is having merge conflict after merging the pull request https://github.com/openBackhaul/OperationKeyManagement/pull/45. Kindly please resolve the merge conflict. Many thanks.

2022-10-12 07:22 UTC, merged