Update Profiles in PList, PInstanceList & CONFIG
openBackhaul/OperationKeyManagement pull request #72
Opened 2022-11-18 17:39 UTC by openBackhaul

2022-11-20 11:59 UTC, IswaryaaS requested changes

2022-11-20 11:59 UTC, IswaryaaS commented on OperationKeyManagement+config.json
> +                    "operation-reference": "/core-model-1-4:control-construct/logical-termination-point=okm-2-0-0-op-s-bs-005/layer-protocol=0/operation-server-interface-1-0:operation-server-interfac
An LTP instance referring "/docs" (okm-2-0-0-op-s-bs-005) and its corresponding reference in client-ltp list of okm-1-0-0-http-s-0000 would need to be added in config.json file

2022-11-20 11:59 UTC, IswaryaaS commented on OperationKeyManagement+config.json
> +                  "description": "List of registered application names and release numbers",
description in line 224 (okm-2-0-0-response-p-007) and 243 (okm-2-0-0-response-p-008) to be changed to "List of release numbers and changes"
path : GenericResponseProfile :: /v1/inform-about-release-history-in-generic-representation :: capability :: description

2022-11-20 11:59 UTC, IswaryaaS commented on OperationKeyManagement+profileInstances.yaml
> +      description: 'List of registered application names and release numbers'
description in line 115 (okm-2-0-0-response-p-007) and 125 (okm-2-0-0-response-p-008) to be changed to "List of release numbers and changes"
path : GenericResponseProfile :: /v1/inform-about-release-history-in-generic-representation :: capability :: description

2022-11-21 08:23 UTC, openBackhaul commented on OperationKeyManagement+config.json
> +                  "description": "List of registered application names and release numbers",
224: Took the value from the ApplicationPattern ("Represents the first entry in the list of releases"). Many thanks for indicating.
243: Changed to "List of release numbers and changes".

2022-11-21 08:24 UTC, openBackhaul commented on OperationKeyManagement+profileInstances.yaml
> +      description: 'List of registered application names and release numbers'
115: Took the value from the ApplicationPattern ("Represents the first entry in the list of releases"). Many thanks for indicating.
125 Changed as proposed.

2022-11-21 09:08 UTC, openBackhaul commented on OperationKeyManagement+config.json
> +                    "operation-reference": "/core-model-1-4:control-construct/logical-termination-point=okm-2-0-0-op-s-bs-005/layer-protocol=0/operation-server-interface-1-0:operation-server-interfac
Changed as proposed.

2022-11-21 09:51 UTC, IswaryaaS submitted a review, later dismissed
Changes looks fine for config.json, ProfileInstances.yaml, profiles.yaml, services.yaml files.
Note : OperationKeyManagement.yaml file is about to be updated with profile related data.

2022-11-21 10:04 UTC, merged