Update Profiles
openBackhaul/OperationKeyManagement pull request #81
Opened 2022-11-23 13:03 UTC by openBackhaul

See issue #71

Fixes #71
Fixes #4

2022-11-23 14:32 UTC, IswaryaaS requested changes

2022-11-23 15:37 UTC, openBackhaul commented on OperationKeyManagement+services.yaml
> +      uuid: okm-2-0-0-http-c-bs-eatl-1-0-0-000
In all applications' specification:
- The release number of the application itself, its NewRelease and the RegistryOffice is put on 2.0.0 .

This requires the RO being updated first.
With every application following the RO, we are testing, whether the upgrade process is working well.
So, there is no plan updating e.g. TAR to -2-0-0-, but the intention to test, whether the update process is working well.

2022-11-23 15:41 UTC, openBackhaul commented on OperationKeyManagement.yaml
> +          https://[/core-model-1-4:control-construct/logical-termination-point=okm-2-0-0-tcp-c-bm-ro-2-0-0-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-
Changes as proposed.

2022-11-24 04:04 UTC, IswaryaaS submitted a review, later dismissed

2022-11-24 08:46 UTC, merged