Update FakeIP addresses and Ports
openBackhaul/OperationKeyManagement pull request #96
Opened 2022-12-06 11:40 UTC by kmohr-soprasteria

Fixes #89

2022-12-08 13:30 UTC, IswaryaaS requested changes
Other than the below comment, changes regarding update fake-ip-address looks fine

2022-12-08 13:30 UTC, IswaryaaS commented on OperationKeyManagement+config.json
> +                    "local-port": 3014
In [service list](https://github.com/openBackhaul/OperationKeyManagement/blob/d8cddb98faf5174d00178331294831d70111985b/OperationKeyManagement%2Bservices.yaml), we can find two instances of tcp-server (tcp-s-bm-000 and tcp-s-bm-001), but in config file, we only have one instance (tcp-s-bm-000). 
Based on latest decision of not considering scenarios for applications outside GCP bubble, tcp instances with "https" protocol (tcp-s-bm-001) became obsolete. 
Please let me know if we can 
proposal 1: remove the values from service.yaml file. (or)
proposal 2: if we can have it as a example that could explain support for https, can we add it to config file as well. Though adding or removing might not have a significant effect, I am asking this just to maintain harmony among files. 
@openBackhaul Kindly please let me know your views

2022-12-09 18:54 UTC, openBackhaul commented on OperationKeyManagement+config.json
> +                    "local-port": 3014
Decided for proposal 1: remove the values from service.yaml file.

2022-12-12 07:16 UTC, IswaryaaS approved these changes

2022-12-12 08:22 UTC, merged